name = "Unicsi Dropshipping"
client_id = "YOUR_CLIENT_ID"
application_url = "https://unicsi.com"
embedded = true
handle = "unicsi-dropshipping"

[access_scopes]
scopes = "read_customers,write_fulfillments,write_inventory,read_inventory,read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://apis.unicsi.com/api/v1/dropshipper/shopify/callback"
]

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "https://apis.unicsi.com/api/v1/dropshipper/shopify/webhooks"